### ISSUE TITLE
Late Constructor Calls

### ISSUE THREAD

**Issue by mal** [simpletest/simpletest#13]
One of the side effects of using the named constructors (<= 1.1.6) was that it was possible to call the `__construct` method, late. The use case for this is for setting/adjusting instance variables on your mock prior to the constructor logic being run. With the move to mocks that use the `__construct` method this is no longer possible.

We're working around that for now with a custom `MockGenerator` that injects the following function into all mocks:

```php
function __constructor() {
    call_user_func_array('parent::__construct', func_get_args());
}
```

This gives us a predictable way to late call the underlying `__construct` on any type of mock. Would you be interested in a PR for this functionality in core?

**Comment by jakoch** [comment]
Hey Mal, sorry for my late response. Yes, we are interested in this PR. Thank you for contributing.
