### ISSUE TITLE
AssertEqual bug

### ISSUE THREAD

**Issue by aliuc** [simpletest/simpletest#15]
Hi. I've been making some PHP recently and I found a bug using SimpleText; here's the way to reproduce it.

```php
class TestBuggy extends UnitTestCase {
    function testShouldBeFalse() {
    	$this->assertEqual(True, 3);
    }
}
```
The code compilates and returns no error, while it should.
Regards,

**Comment by perrick** [comment]
I'm sorry but this is the intended behaviour ;-) I know it seems counter-intuitive but PHP works the same way as far as the == sign is used. (ie. True == 3). Now if you want it to return false, you may need to use $this->assertIdentical(True, 3); (ie. in PHP terms : True === 3).
Yours,

**Comment by aliuc** [comment]
I tried that, and it worked perfectly. Thanks for the help.
