### ISSUE TITLE
Dynamic method called as static

### ISSUE THREAD

**Issue by guicara** [simpletest/simpletest#16]
Hello,

I think there is a problem with some dynamic methods that are called as static methods. And calling a dynamic method statically generates the E_STRICT error with PHP 5. Could you please check that and update Simpletest?

The following dynamic methods are called statically:

  * Class PageRequest, methods get() and post()
  * Class DOMDocument, method loadHTML

```
vendor/simpletest/simpletest/test/site/front_controller_style/show_request.php:21
vendor/simpletest/simpletest/test/site/front_controller_style/show_request.php:35
vendor/simpletest/simpletest/test/site/path/network_confirm.php:41
vendor/simpletest/simpletest/test/site/network_confirm.php:41
vendor/simpletest/simpletest/test/site/protected/network_confirm.php:41
vendor/simpletest/simpletest/test/site/path/network_confirm.php:55
vendor/simpletest/simpletest/test/site/protected/network_confirm.php:55
vendor/simpletest/simpletest/test/site/network_confirm.php:61
vendor/simpletest/simpletest/extensions/coverage/test/coverage_calculator_test.php:70
vendor/simpletest/simpletest/extensions/coverage/test/simple_coverage_writer_test.php:71
```

This issue is similar to issue #2.

Thanks ;)

Guillaume

**Comment by jakoch** [comment]
Hey Guillaume, thank you for bug-reporting. We will look into the issue.

**Comment by GuillaumeMB** [comment]
Hello jakoch,

You're welcome ;)

Any news regarding the issues on `simpletest/test/sites/*`?
If you wish I can make a pull requests.

Thanks,

Guillaume

**Comment by guicara** [comment]
Hello jakoch,

You're welcome ;)

Any news regarding the issues on simpletest/test/sites/*?
If you wish I can make a pull requests.

Thanks,

Guillaume

**Comment by jakoch** [comment]
Hey Guillaume,

yes, there are some news: i've re-enabled the acceptance tests for  `simpletest/test/sites/*`
and removed some errors and notices along the way. 
We could now also remove the static calls, e.g. `PostRequest:get()`. 

It would be very helpful, when you find the time to send some pull requests.
I really appreciate any help.

Thanks, Jens

**Comment by guicara** [comment]
Hello jakoch,

Methods `get()` and `post()` of the `PostRequest` class are now static methods since your last commit bec40cc8cc0c5a96ce4087b9db78a12ebc89d27d. So I think the problem is resolved? I do not understand the benefits of removing the static calls.

Thanks,

Guillaume

**Comment by jakoch** [comment]
Yes, its resolved.

I've added static to solve the initially reported E_STRICT issue: calling dynamic method statically.
Now "static" itself is often problematic, because it introduces global state and makes things hard(er) to test, but (sometimes) faster. The benefits of removing static calls is to improve test-ability in the long run. But as you can see: i've used the simple fix for the problem.. ;) 

Thank you for raising the issues.
Best, Jens
