### ISSUE TITLE
Eclipse. Dynamic method called as static 

### ISSUE THREAD

**Issue by trom58al** [simpletest/simpletest#2]
Location:
simpletest/eclipse.php
EclipseReporter::escapeVal($output) . '"}'); (at line 303)

```
            $result = $this->listener->write('{status:"info",message:"' .
                                              EclipseReporter::escapeVal($output) . '"}');
```

Problem:
Dynamic method called as static

Pull request:
https://github.com/simpletest/simpletest/pull/3

**Comment by jakoch** [comment]
https://github.com/simpletest/simpletest/pull/3 was merged. Closing.
