### ISSUE TITLE
Example simpletest for psr-4

### ISSUE THREAD

**Issue by StephanKrauss** [simpletest/simpletest#24]
Hello,

I look for a example of simpletest with namespaces.
I'm a beginner in unit testing.
How can help ?

Your sincerly

Stephan

**Comment by jakoch** [comment]
Hello Stephan.
Sorry for the delayed response.

SimpleTest itself is not using namespaces.
When you fetch the project via Composer SimpleTest will be installed into the `vender/simpletest/simpletest` folder. The files of SimpleTest reside in this directory 
and are automatically included via a classmap include, see https://github.com/simpletest/simpletest/blob/master/composer.json#L56
In other words: while your project might use PSR-4 or PSR-0, the files of SimpleTest are in Composers classmap. 

Hope this helps a bit. 
If you have follow up questions, feel free to ask.

Regards, Jens
