### ISSUE TITLE
release 1.01

### ISSUE THREAD

**Issue by thekaduu** [simpletest/simpletest#27]
Hey guys, I'm needing the simpletest release 1.01, 'Cauz  using cakephp 1.3. This framework uses simpletest 1.01 (Yeap, i know :S) and i'm trying to make composer.json  with simpletest but i didnt find  this version.

**Comment by jakoch** [comment]
Hey Carlos!

You find old releases are on Sourceforge: https://sourceforge.net/projects/simpletest/files/simpletest/
I guess you mean v1.0.1. That's a really old one from 2008-04-08. It has only a handful of downloads.

Regards, Jens

**Comment by thekaduu** [comment]
Thanks Jens, i'll to download this.
