### ISSUE TITLE
Integration with NetBeans

### ISSUE THREAD

**Issue by michalk-k** [simpletest/simpletest#30]
Do you have any plans to integrate Simpletest with NetBeans?
Currently I have no idea about requirements of such integration. For sure it all about writing NB plugin which can process simpletest output.

with regards

**Comment by jakoch** [comment]
Hey!
Thank you for this feature request.
No, at the moment, there are no plans to write a Simpletest plugin for NetBeans.
But it's a great idea and would help the community a lot. 
I can only encourage you to contribute.

**Comment by jakoch** [comment]
Nice to have, but out of scope for the project.
