### ISSUE TITLE
mock_object is trying to run tell() on non existing object

### ISSUE THREAD

**Issue by vaceletm** [simpletest/simpletest#38]
How to reproduce ?

Instanciate a mock in a constructor or run:

    $> php test/mock_objects_test.php
    PHP Fatal error:  Uncaught Error: Call to a member function tell() on null in /.../vendor/simpletest/simpletest/mock_objects.php:711

**Comment by vaceletm** [comment]
Great, when do you think this will be part of a stable release ?

**Comment by jakoch** [comment]
I can't give an estimate.
There is still a lot of work to do, including fixing the reference handling, fixing the mock handling and adding support for PHP 7 on the mocking layer.

**Comment by vaceletm** [comment]
OK.
Thx anyway for the hard work on this project maintenance !
