### ISSUE TITLE
composer warning: Ambiguous class resolution; file for autoloading is chosen at random

### ISSUE THREAD

**Issue by sapphirecat** [simpletest/simpletest#4]
> Warning: Ambiguous class resolution, "SimpleReflection" was found in both "vendor/simpletest/simpletest/reflection_php4.php" and "vendor/simpletest/simpletest/reflection_php5.php", the first will be used.

Composer seems to iterate in filesystem order, so this class effectively gets chosen at random on each distinct installation, although the `php5` variant is the correct one in my environment.

I don't think this makes a difference (the class isn't actually autoloaded, so if the wrong one was in the autoloader, nothing bad happens) unless client code accidentally triggers the autoload before SimpleTest gets a chance to do its own direct loading. Still, I would like the warning to be fixed.

In fact, I think the `php4` file can just be deleted. `composer.json` and the bundled docs both say 1.1+ are PHP5-only, and I can't find anywhere that _would_ load the `php4` variant.

**Comment by jakoch** [comment]
> In fact, I think the php4 file can just be deleted.

Allright, i've dropped the file and it's test.

**Comment by lxlang** [comment]
Can you create a new version including this fix?

**Comment by VasuLief** [comment]
+1

**Comment by stockii** [comment]
:+1:

**Comment by zaratozom** [comment]
:+1:

**Comment by GuillaumeMB** [comment]
Any news regarding this matter?

**Comment by jakoch** [comment]
>Can you create a new version including this fix? 
I've released a new tag v1.1.7 including these changes.

**Comment by GuillaumeMB** [comment]
On my composer.json file when I add `"simpletest/simpletest": "^1.1"`, version 1.1.6 of simpletest is installed. I don't understand why because the new tag 1.1.7 is available on Packagist.

**Comment by jakoch** [comment]
I've tested the issue you reported, but was unable to reproduce it.
I've used the following `composer.json`:

    {
        "require": {
		"simpletest/simpletest": "^1.1"
	}
    }

Then `composer install -vvv --profile` and this fetches v1.1.7.
