### ISSUE TITLE
dumper->clipString() is multibyte safe?

### ISSUE THREAD

**Issue by TrueType** [simpletest/simpletest#44]
Hi. I guess not. It will cut UTF-8 text in parts, which may contain invalid "characters" at the end. A part of a multibyte characters. Comes in rare cases only... if you work with "ä,ß,.." or else. Simply use mb_strlen, mb_substr.

**Comment by jakoch** [comment]
Thank you for reporting this issue, Henri. 
Feel free to send PullRequests.
