### ISSUE TITLE
Unable to click submit when there is onclick tag

### ISSUE THREAD

**Issue by bishu** [simpletest/simpletest#53]
$browser->clickSubmit("Submit");
or
$browser->clickSubmitByName("submitAction");

is not working on the following code -

`<input type="submit" value="Submit" name="submitAction" onclick="return validate()">`

**Comment by TrueType** [comment]
oh well. That click would then run some javascript. But simpletest does not do javascript. So it looks like a dead end here.

**Comment by jakoch** [comment]
Please use one of the front-end testing tools: Selenium or PhantomJS or Chrome headless.
Closing.
