### ISSUE TITLE
Syntax error in mocked methods in PHP 7.1+

### ISSUE THREAD

**Issue by zerocrates** [simpletest/simpletest#56]
Replacing my ancient bug report with an up-to-date one:

reflection.php has [code for generating a nullable return type](https://github.com/simpletest/simpletest/blob/master/reflection.php#L374-L377) in a method signature, but the code seems to have 2 problems:

1. It doesn't actually use allowsNull() on the return type object, so it looks like all types would be marked nullable
2. More relevantly, It doesn't check to see if `getReturnType` returns null (or is empty string in the casted-to-string form it's currently being used), so in that case it generates a signature with just a floating `: ?`, which causes a syntax error when the code gets eval'd in a mock class.

Just removing the whole block removes the syntax error and is probably a step forward.

**Comment by jakoch** [comment]
Hey John!
Thank you for reporting the issue.
The master branch isn't stable. Reflection and Mocking are broken.
Please contribute by sending the bugfix(es) as PR(s).

**Comment by gaboto83** [comment]
What about changing this lines:
            if(PHP_VERSION_ID >= 70100) {
                $returnType = '?'.$returnType;
            }
With these:
            if(PHP_VERSION_ID >= 70100 and $returnType != '') {
                $returnType = '?'.$returnType;
            }

**Comment by asmundstavdahl** [comment]
Fixed with #62 by commit 881b533.
