### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by tbreuss** [simpletest/simpletest#82]
Is this project still alive? I ask because the linked website is broken and therefore no documentation is available.

If it is still alive:
- [simpletest.org](http://simpletest.org/) should be brought back to life
- or an action should be added to render and deploy documentation to gh pages
- and of course code base should be updated to support recent php versions

It it is not alive:
- the project should be archived
- all links to [simpletest.org](http://simpletest.org/) should be removed

**Comment by lastcraft** [comment]
Hi...

On 21/01/2024 06:50, tebe wrote:
>
> Is this project still alive? I ask because the linked website is 
> broken and therefore no documentation is available.
>
Unfortunately, I haven't coded in PHP for about 15 years. If someone 
woudl like to host, I am happy to repoint the domain and regenerate the 
docs.
>
> If it's alive:
>
>   * simpletest.org <http://simpletest.org/> should be brought back to life
>
I still have the domain. I guess I can point it at github.
>
>   * or an action should be added to render and deploy documentation to
>     gh pages
>
There are only about 9 doc pages and 8 tutorial pages.
>
>   * and of course code base should be updated to support recent php
>     versions
>
Yep

  As Simpletest was one of the first mock object libraries ever (and 
first for PHP), the mocks interface could do with a bit of an upgrade. 
The web tester already supporeted Selenium, but I suspect that needs 
fixing as well.

> It it's not alive:
>
>   * the project should be archived
>   * all links to simpletest.org <http://simpletest.org/> should be removed
>
The people who worked on it would probably like CV links, etc. The 
tutorial is also pretty generic.

If anyone volunteers to resuscitate the project, I am happy to help. The 
days of me being an active PHP dev are long gone though.

yours, Marcus

**Comment by tbreuss** [comment]
FYI: I asked because I see this and similar projects as a lightweight alternative to PHPUnit and other heavyweight testing frameworks.
