### ISSUE TITLE
Cannot install v1.2.0 with PHP 8.x

### ISSUE THREAD

**Issue by tbreuss** [simpletest/simpletest#83]
Although there is a version 1.2.0, it cannot be installed on a system with PHP 8.x.

Request for v1.2 fails

<img width="1128" alt="installation_1" src="https://github.com/simpletest/simpletest/assets/1334161/21a7d831-e894-49fb-b4eb-1d1a4895df1c">

Request for 1.1.7 is successful

<img width="1121" alt="installation_2" src="https://github.com/simpletest/simpletest/assets/1334161/6f67ef82-af3c-40bf-b6e3-a91d9db3d171">

**Comment by jakoch** [comment]
Yes, SimpleTest v1.2 has a PHP version constraint `^7.1`, which is equivalent to `>=7.1.0 <8.0.0`.
Referencing: https://github.com/simpletest/simpletest/blob/v1.2.0/composer.json#L51-L53
Your PHP version is `8.3.7`, which is above the version constraint range and so it fails.

We don't have a release (or tagged version) with a higher PHP version constraint.

The SimpleTest main branch addds a logical OR with PHP 8 version constraint.
Referencing: https://github.com/simpletest/simpletest/blob/main/composer.json#L51-L53
You can fetch it using `composer require simpletest/simpletest:dev-main --dev`.

**Comment by tbreuss** [comment]
👍 Sorry for the inconvenience and thanks for the reply. I really should have noticed that.
